sudo: required
services:
  - docker

script:
  - echo ${TRAVIS_COMMIT:0:7} | $(date +%Y%m%d)
  - DTAG=${TRAVIS_COMMIT:0:7} DARGS="--build-arg BASE_CONTAINER=ubuntu" make build/qwer 

after_script:
  - docker images
