sudo: required
services:
  - docker

script:
  - echo "commit:" ${TRAVIS_COMMIT:0:7}
  - echo "date:  " $(date +%Y%m%d)
  - DTAG=${TRAVIS_COMMIT:0:7} DARGS="--build-arg BASE_CONTAINER=ubuntu" make build/qwer 

after_script:
  - docker images
