sudo: required

services:
  - docker

env:
  global:
    - OWNER=dddlab              # should match OWNER in Makefile
    - JUPYTER_TAG=678ada768ab1  # jupyter docker-stack tag: e.g. jupyter/scipy-notebook:${JUPYTER_TAG}
    - DTAG="v$(date +%Y%m%d)-${TRAVIS_COMMIT:0:7}-${JUPYTER_TAG}"
    - secure: o4FUa4TIwWHHmXVFgQkK6m3psKSYho25IV1S/9UDuLR8cyFdRDU4duMvvrwALRn3ih6vrZoebQWIJsch+wB+idshi9ldibqfwnf/Dv8KhrRpTbNruxWQWatzlUo4/S/hnz10QQHssdJ04zzPv7FxVKmmlOEYqhYs6KjX1H9CD2ixFaMhx+/Zdo9MK1HOpILIvJ9ocTQFGSu/2eMPkYQl3t9yvKqGc5c0Z/SR9+OzkL1nZ4LEnM+rLqMNjpt4E0JoaXk+vILKo3u9rq7ERkzpRf7zFUYx8Te1viWyyWeeL76AFLEEsQ8NHZz01Zlg7Qg0z3qOzeGvRRCFAONatoNmT9mDXecM1RvsOjp2IKt4MvxLRNPUYyIcsteA+8isaBNcdOzcBjyGQ/M95zAxTt3Xdjq24Sfl3ZkcNtBZGFOKFoxhXqj6ABBbsoRbMERDEaG69AHnEoSQKYbaGQuPP7nKlxDs8eCPXRfJQG9iq1T6pOecAoY18KK8Rh9oqJUkxMno5db10ULR09Se6f7TCWwcSJxCXlGF9I02RMp8bpHAV9fHRx90qIviDBMi66yjz2tudvsfgXMND6sVjN7+GPyL4XsmGBLgg2zS+rhtJrLpGy4HMTeyNQ2cx53KmG6avw6vkkQb6QFk6dKqzLmU9ksk1KrxfZsFlQpEmk4zgN1IhLY=
  
jobs:
  include:
    - stage: jupyter-base-images
      script: 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull  jupyter/scipy-notebook:${JUPYTER_TAG}
        - docker tag   jupyter/scipy-notebook:${JUPYTER_TAG} ${OWNER}/scipy-notebook:${DTAG}
        - docker push ${OWNER}/scipy-notebook:${DTAG}
    - script: 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull  jupyter/r-notebook:${JUPYTER_TAG}
        - docker tag   jupyter/r-notebook:${JUPYTER_TAG} ${OWNER}/r-notebook:${DTAG}
        - docker push ${OWNER}/r-notebook:${DTAG}
    - stage: dddlab-base-images
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; DTAG=${DTAG} DARGS="--build-arg BASE_IMAGE=${OWNER}/scipy-notebook:${DTAG}" make build/base-scipy
    - script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; DTAG=${DTAG} DARGS="--build-arg BASE_IMAGE=${OWNER}/r-notebook:${DTAG}"     make build/base-rstudio
    - stage: dddlab-user-images-1
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; DTAG=${DTAG} DARGS="--build-arg BASE_IMAGE=${OWNER}/base-scipy:${DTAG}"     make build/base-scipy-rstudio
      
after_script:
  - docker images
