sudo: required
services:
  - docker

script:
  - echo ${TRAVIS_COMMIT:0:7}
  - echo v$(date +%Y%m%d).${TRAVIS_COMMIT:0:7}
  - docker build --tag myimage:v$(date +%Y%m%d).${TRAVIS_COMMIT:0:7} base-scipy/

after_script:
  - docker images
